# Generated by Django 3.0.1 on 2020-01-01 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagicSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_id', models.UUIDField()),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('watched', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MagicCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('magic_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoilers.MagicSet')),
            ],
        ),
    ]
