# Generated by Django 3.0.1 on 2020-01-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoilers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiccard',
            name='scryfall_id',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='magicset',
            name='scryfall_id',
            field=models.UUIDField(unique=True),
        ),
    ]
