# Generated by Django 3.0.3 on 2020-04-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoilers', '0002_auto_20200102_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicset',
            name='icon_svg_uri',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
