# Generated by Django 3.0.3 on 2020-04-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spoilers', '0003_magicset_icon_svg_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiccard',
            name='magic_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='spoilers.MagicSet'),
        ),
    ]
