# Generated by Django 3.0.1 on 2020-01-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='supports_manamoji',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
