# Generated by Django 3.0.7 on 2020-09-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0002_channel_supports_manamoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('SL', 'Slack'), ('EC', 'Echo (for testing)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='channel',
            name='webhook_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
