# Generated by Django 3.2.2 on 2021-05-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0003_auto_20200922_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('SL', 'Slack'), ('DI', 'Discord'), ('EC', 'Echo (for testing)'), ('TE', 'Test (for testing)')], max_length=2),
        ),
    ]
