# Generated by Django 3.2.2 on 2021-05-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0004_alter_channel_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='manamoji_style',
            field=models.CharField(choices=[('NO', 'None'), ('HY', 'Hyphenated'), ('NH', 'Non-hyphenated')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('EC', 'Echo (for testing)'), ('SL', 'Slack'), ('DI', 'Discord'), ('TE', 'Testing')], max_length=2),
        ),
    ]
